# Generated by Django 4.2.1 on 2023-05-19 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0005_rename_personnel_equipe_personnels'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetrealise',
            name='equipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artyprod.equipe'),
        ),
    ]
