# Generated by Django 4.2.1 on 2023-05-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0006_projetrealise_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetrealise',
            name='personnels',
            field=models.ManyToManyField(to='artyprod.personnel'),
        ),
    ]
