# Generated by Django 4.2.1 on 2023-05-20 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0008_remove_projetrealise_personnels'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetrealise',
            name='date_realisation',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
