# Generated by Django 4.2.1 on 2023-05-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0011_rename_cvprs_personnel_cvprs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='photoPrs',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
