# Generated by Django 4.2.1 on 2023-05-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0013_rename_fichier_linkedln_personnel_linkedln'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='servPhoto',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
