# Generated by Django 4.2.1 on 2023-05-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0014_service_servphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='prjphtonr',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
