# Generated by Django 4.2.1 on 2023-05-23 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0015_projet_prjphtonr_delete_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], max_length=20)),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artyprod.equipe')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artyprod.service')),
            ],
        ),
    ]
