# Generated by Django 4.2.1 on 2023-05-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0019_demandeprojet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeprojet',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='demandeprojet',
            name='statut',
        ),
    ]
