# Generated by Django 4.2.1 on 2023-05-23 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0020_remove_demandeprojet_equipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeprojet',
            name='user',
        ),
    ]
